d3d9.supportDFFormats = true
d3d9.forceSamplerTypeSpecConstants = false
d3d9.supportX4R4G4B4 = true
d3d9.deferSurfaceCreation = false
d3d9.cachedWriteOnlyBuffers = true
d3d9.floatEmulation = Strict
d3d9.invariantPosition = true
d3d9.memoryBudget = 1024
d3d9.maxAvailableMemory = 2048
dxvk.enableGraphicsPipelineLibrary = False
dxvk.hud = 0
dxvk.tearFree = True
dxvk.transparentSkipSampleShading = true
dxvk.numCompilerThreads = 1

